/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab12storybook;

/**
 *
 * @author luzhernandez
 */
public class EndFrame extends javax.swing.JFrame {
    
    private StorybookModel myModel;
    private boolean choseDoor1 = false;
    
    
    /**
     * Creates new form EndFrame
     */
    public EndFrame(StorybookModel model) {
        initComponents();
        this.myModel = model;
        welcomeLabel.setText("Welcome, " + myModel.getUserName() + ".");
        crimeLabel.setText("You have been accused of " + myModel.getCrime() + ".");
        instructionLabel.setText("Pick a door to determine your verdict.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        crimeLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        leftDoorButton = new javax.swing.JButton();
        rightDoorButton = new javax.swing.JButton();
        exitTirbunalButton = new javax.swing.JButton();
        nextTrialButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome");

        crimeLabel.setText("Crime");
        crimeLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                crimeLabelKeyTyped(evt);
            }
        });

        instructionLabel.setText("instruction");

        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Door.GIF"))); // NOI18N
        leftDoorButton.setBorderPainted(false);
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });

        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Door.GIF"))); // NOI18N
        rightDoorButton.setBorderPainted(false);
        rightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorButtonActionPerformed(evt);
            }
        });

        exitTirbunalButton.setText("Exit Tirbunal");
        exitTirbunalButton.setEnabled(false);
        exitTirbunalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTirbunalButtonActionPerformed(evt);
            }
        });

        nextTrialButton.setText("Next Trial");
        nextTrialButton.setEnabled(false);
        nextTrialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTrialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instructionLabel)
                            .addComponent(crimeLabel)
                            .addComponent(welcomeLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitTirbunalButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightDoorButton)
                            .addComponent(nextTrialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crimeLabel)
                .addGap(18, 18, 18)
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rightDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(leftDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitTirbunalButton)
                    .addComponent(nextTrialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
        // TODO add your handling code here:
        choseDoor1=true;
        if(choseDoor1){
            rightDoorButton.setEnabled(false);
        }
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Tiger.GIF"))); // NOI18N
        instructionLabel.setText("You are GUILTY! Prepare to be eaten!");
        
        choseDoor1=true;
        if(choseDoor1=true){
            exitTirbunalButton.setEnabled(true);
           nextTrialButton.setEnabled(true);
        }
 
    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void rightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorButtonActionPerformed
        // TODO add your handling code here:
        choseDoor1=true;
        if(choseDoor1){
            leftDoorButton.setEnabled(false);
        }
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Lady.GIF"))); // NOI18N
        instructionLabel.setText("You are INNOCENT! Sorry about that. Please accept this lady.");
        
        choseDoor1=true;
        if(choseDoor1=true){
            exitTirbunalButton.setEnabled(true);
           nextTrialButton.setEnabled(true);
        }
   
    }//GEN-LAST:event_rightDoorButtonActionPerformed

    private void crimeLabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crimeLabelKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_crimeLabelKeyTyped

    private void exitTirbunalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTirbunalButtonActionPerformed
        // TODO add your handling code here:
        choseDoor1=true;
        if(choseDoor1=true){
            exitTirbunalButton.setEnabled(true);
           nextTrialButton.setEnabled(true);
        }
        System.exit(0);
    }//GEN-LAST:event_exitTirbunalButtonActionPerformed

    private void nextTrialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialButtonActionPerformed
        // TODO add your handling code here:
        choseDoor1=true;
        if(choseDoor1=true){
            exitTirbunalButton.setEnabled(true);
            nextTrialButton.setEnabled(true);
        }
        StartFrame myStartFrame = new StartFrame(myModel);
        myStartFrame.setVisible(true);
//        myEndFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextTrialButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crimeLabel;
    private javax.swing.JButton exitTirbunalButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JButton nextTrialButton;
    private javax.swing.JButton rightDoorButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
